### PR TITLE
Smseifi profile branch

### PR DESCRIPTION
**Pull request by smseifi**
Submitting profile information for Mohsen Seifi

### CODE REVIEW

**Comment by ccontrer** [comment]
Hi Mohsen,

Perhaps the same issue with `<` and `>` as in #25 ?

Try removing all of those characters.

**Comment by ianabc** [comment]
Yep, I think @ccontrer has it. If you remove those characters this should be ready to go. As an example, your first few lines should look like
```
---
# Display name
title: Mohsen Seifi
```
NOT
```
---
# Display name
title: <Mohsen Seifi>
```

Once you've done that for the other lines just hit commit and the PR should automatically update. I think the PR is ready to go after that.

**Comment by ianabc** [comment]
That looks great Mohsen, thank you! Merging

**Comment by smseifi** [comment]
Hi there,


Sorry for my late response, I was AFK. I just did what you suggested. Only question is should I make a pull request after that? Because I tried to make a pull request and I couldn't.


Best wishes,

Mohsen

________________________________

**Comment by smseifi** [comment]
Thank you!

**Pull request merged**
