### PR TITLE
Added member profiles

### PR DESCRIPTION
**Pull request by ccontrer**

### CODE REVIEW

**Comment by ianabc** [comment]
This might be a little trickier than the stuff yesterday, I think you'll need to pull origin/master to make some of the authors visible (e.g. li-keran isn't in ccontrer:master yet). Are you comfortable doing that? I think it should pull cleanly because all of the changes are isolated in different files.

**Comment by ccontrer** [comment]
Yes, I thought of that. I figured it would work under pimsmath:m2pi.ca, but not under my fork. I'll pull origin/master.

**Comment by ccontrer** [comment]
It should be good now.

**Comment by ianabc** [comment]
Yep, that looks good to me. Thank you for this!

**Pull request merged**
