### PR TITLE
Create _index.md

### PR DESCRIPTION
**Pull request by Brian-T-Chan**
Submitting profile information for Ian Allison.

### CODE REVIEW

**Comment by ianabc** [comment]
Hi Brian,

In my notes for the first part of the class I should have been clearer in how to make the replacements in _index.md. Your variables shouldn't be surrounded by angle brackets, e.g. do
role: Graduate Student
NOT
role: <GRADUATE STUDENT>
i.e. remove the < and the >.  You can just update the file in that branch and hit commit and it should automatically update the PR. This is a pretty standard thing, commonly you'll want to make minor changes after initially opening the PR based on feedback from the maintainers or improvements you've spotted. You can keep making changes up until the PR is merged. After it is merged you can always open another PR with any extra changes

**Comment by ianabc** [comment]
Sorry, one more thing can you add a photo or avatar picture and call it
```
content/authors/Brian-T-Chan/avatar.jpg
```
If you  don't want to use a photo of yourself you can grab a [generic avatar](https://m2pi.ca/authors/akcora/avatar.jpg) instead, just make sure the filename matches the pattern above and we should be good to go!

**Comment by Brian-T-Chan** [comment]
Just did it! Please let me know if I missed something.

**Comment by ianabc** [comment]
Looks great, thanks Brian. I'll merge this now.

**Pull request merged**
