### PR TITLE
umaaron profle branch 

### PR DESCRIPTION
**Pull request by umaaron**
Submitting profile information fro Xiang(Aaron)zheng.

### CODE REVIEW

**Comment by ianabc** [comment]
I think you might have created the file in the wrong place, I think it should be

```
content/authors/umaaron/_index.md
```

You should be able to fix that by clicking edit on the file and the changing the file name.

Also, some of the content is missing from the `_index.md` file. It might be best to copy/paste [the template](https://gist.githubusercontent.com/ianabc/9f3973091fe1788e780236e1ace03c49/raw/a461969c5b110b68095c29fcd0f651275e5b6362/index-md) and edit it.

**Comment by umaaron** [comment]
Hello Lan,

Do not know why can not edit the file name, it’s there way I can figure out ? Thanks.

2020年8月12日 下午4:07，Ian Allison <notifications@github.com<mailto:notifications@github.com>> 写道：



I think you might have created the file in the wrong place, I think it should be

content/authors/umaaron/_index.md


You should be able to fix that by clicking edit on the file and the changing the file name.

Also, some of the content is missing from the _index.md file. It might be best to copy/paste the template<https://gist.githubusercontent.com/ianabc/9f3973091fe1788e780236e1ace03c49/raw/a461969c5b110b68095c29fcd0f651275e5b6362/index-md> and edit it.

**Comment by ianabc** [comment]
I think I've managed to rename the file so that it is in the right location. Can you try adding a photo or avatar picture to the same directory? It should be called `content/authors/umaaron/avatar.jpg`. Once that is done you can hit commit and the PR should be automatically updated. If you don't want to use a picture of yourself you can grab a [generic avatar image](https://m2pi.ca/authors/akcora/avatar.jpg) and upload that instead, just make sure you add it to the right location.

**Comment by umaaron** [comment]
Hello lan,

Sorry, I'm new in Github, I may delete my files  by accidentally, couldn't find anymore can I create it again ?

Best regards
Aaron

________________________________

**Comment by ianabc** [comment]
There was a merge conflict because I merged your other PR (#70) and they both wanted to change the same file. I compared them and I think I've figured out the right set of changes. Take a look at the [preview](https://deploy-preview-35--mathtopowerindustry.netlify.app/authors/umaaron/) and let me know if it looks OK, if it does I can merge this one as well. This sort of thing is one of the main reasons that git exists, projects change all the time and git has tools to help you navigate through those changes.

**Comment by umaaron** [comment]
Hey lan,

Can you use that newest one please?

Thank you so much for helping!  I really need take time to lean GitHub. Thank you so much !

Best regards
Aaron

________________________________

**Comment by ianabc** [comment]
Cool, merging now.

**Pull request merged**
